### ISSUE TITLE
Doesn't fit screen in landscape mode.

### ISSUE THREAD

**Issue by robertonic** [aagarwal1012/IntroViews-Flutter#1]
When orientation is switched to landscape mode the flutter overflow black and yellow bar is shown.

**To Reproduce**
1. Change device orientation to landscape while viewing Intro-Views

**Expected behavior**

It would be preferable if the layout changed to fit title, image and controls.

**Comment by aagarwal1012** [comment]
Well, good to see the `first issue`.
I have made this by assuming it in Portrait Mode. I haven't tested it for the landscape mode.
I will definitely work upon it, if you like, you can also contribute to this project.

**Comment by robertonic** [comment]
Thank you!

Just tried the update and it works perfectly.

As a workaround before I was forcing the IntroViews to stay in portrait
mode.

Rob

**Comment by robertonic** [comment]
Just tried the update and IntroViews now works perfectly in landscape mode.  Thank you.

**Comment by aagarwal1012** [comment]
@robertonic, PageBubble is a widget, you can specific the height and width of container while passing in the constructor.
