### ISSUE TITLE
Body text aligns to bottom

### ISSUE THREAD

**Issue by rajeevjaiswal** [aagarwal1012/IntroViews-Flutter#13]
@aagarwal1012 Please refer the screenshot 
![p_20180916_110911](https://user-images.githubusercontent.com/8944920/45593308-31bad080-b9a1-11e8-9911-4d92e77e6fe5.jpg)

I want the title to be empty so I tried to pass null but that did not work, so I passed an empty text.
The body text is at the bottom I want it below the image as shown in your demo

**Comment by aagarwal1012** [comment]
@taljacobson can you help out here ?

**Comment by taljacobson** [comment]
i can look into it more deeply during the week.
but it seems like we'll need to expose a way to change [this Column props](https://github.com/aagarwal1012/IntroViews-Flutter/blob/master/lib/UI/page.dart#L41) if i understand @rajeevjaiswal  needs.

**Comment by rajeevjaiswal** [comment]
@taljacobson  Yes the widgets alignment needs to be exposed .  It will be better for customization

**Comment by aagarwal1012** [comment]
@rajeevjaiswal refer the pull request #14 
I think this issue is now resolved so I am closing it.
