### ISSUE TITLE
Next Button

### ISSUE THREAD

**Issue by Lopics** [aagarwal1012/IntroViews-Flutter#21]
Feature:
Adding a next button for the user to move to the next screen rather than only having swipe. 

I have already implemented the feature. However, I cannot create a new branch to pull the code (I am not a contributor).

Screenshot:
<img width="547" alt="screen shot 2018-12-23 at 3 15 49 pm" src="https://user-images.githubusercontent.com/4427929/50387235-a9e21200-06c5-11e9-84e5-f30f3c158275.png">

**Comment by taljacobson** [comment]
i don't understand the comment about not being able to branch and create a pull request.
where did you add the feature.

maybe it be best to fork the repository through the fork button at the top of the Github page, clone to your machine and push the changes to your fork on Github.
then you should be able to submit a pull request so we can evaluate.

as with the feature.
a next button could make sense, 
but might colide with the existing `doneButtonPersist` prop that keeps the done button and its functionality throughout all screens.
should said `doneButtonPersist` be deprecaded or overriden by it.

**Comment by aagarwal1012** [comment]
@taljacobson, thanks for your concern. Hope you will solve these issues and merge the pull requests soon.
