### ISSUE TITLE
Title Text is Hidden

### ISSUE THREAD

**Issue by nikhiljha** [aagarwal1012/IntroViews-Flutter#29]
**Describe the bug**
The title text of the page is sometimes hidden.

**To Reproduce**
1. Get an SVG from Undraw.co
2. Display the SVG like so...

```dart
class Intro extends StatelessWidget {
  final pageList = [
    PageViewModel(
      pageColor: const Color(0xFF607D8B),
      iconImageAssetPath: 'assets/baseline_alarm_black_24dp.png',
      //iconColor: null,
      //bubbleBackgroundColor: null,
      body: Text(
        'Testing',
      ),
      title: Text('Scheduling'),
      mainImage: SvgPicture.asset(
        'assets/timemng.svg',
        height: 285.0,
        width: 285.0,
        alignment: Alignment.center,
      ),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IntroViewsFlutter(
      pageList,
      onTapDoneButton: (){
        //Void Callback
      },
      showSkipButton: true,
      pageButtonTextStyles: new TextStyle(
          color: Colors.white,
          fontSize: 18.0,
          fontFamily: "Regular",
        ),
    ),
    );
  }
}
```
3. The text overlaps.

**Expected behavior**
The text should be "on top of" the SVG.

**Screenshots**
<img width="584" alt="Screen Shot 2019-03-21 at 11 39 02 AM" src="https://user-images.githubusercontent.com/2773700/54776716-eee6e900-4bcd-11e9-8af6-eea9f013a141.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone XR (Emulator)
 - OS: [e.g. iOS8.1] 12.1

**Additional context**
N/A

**Comment by aagarwal1012** [comment]
@nikhiljha, I think you should crop the image, i.e., remove the extra blank space around the image and try again.

**Comment by NathanAP** [comment]
This actually seems like a bug. I use this package since last year and only this month these situations started to appear. I have no space around the image and it still getting the title text space...

**Comment by marloncepeda** [comment]
Hi! the solution a your problem is edit de files in the library:

lib/UI/page.dart in widget _TitlePageTransform  

padding: 60 to 5.0.

**Comment by aagarwal1012** [comment]
#31 solves this issue.

**Comment by thomasuebi** [comment]
Title now sticking in the very top border ... is there a way to make it look less ugly?

![image](https://user-images.githubusercontent.com/23338437/59214381-471efd00-8bb7-11e9-9adb-6208fecc4601.png)

Version 2.6.0
