### ISSUE TITLE
Safe area - It doesn't render properly on iPhones with notch

### ISSUE THREAD

**Issue by uwagh** [aagarwal1012/IntroViews-Flutter#30]
**Describe the bug**
Safe area - It doesn't render properly on iPhones with notch

**To Reproduce**
1. Run on any iPhone devices with a notch

**Expected behavior**
Implement safe area

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhoneX

**Comment by aagarwal1012** [comment]
@uwagh, can you post some screenshots?

**Comment by Ahmadre** [comment]
Just add: 
`SafeArea(
    child: new IntroSlider(...)
);
`
to your build method ^^ that is not a bug, you just forgot to wrap it in a SafeArea

**Comment by marianoarga** [comment]
@Ahmadre 's Fix works

**Comment by aagarwal1012** [comment]
@marianoarga, thanks for the confirmation. Now, I am closing this issue.
