### ISSUE TITLE
Rapid clicks on `NEXT` and `BACK` produce flutter error

### ISSUE THREAD

**Issue by kengu** [aagarwal1012/IntroViews-Flutter#54]
**Describe the bug**
Rapid clicks on `NEXT` and `BACK` buttons increments internal index out of range producing a flutter error.

**To Reproduce**
1. Enable `NEXT` or `BACK` buttons
2. Click several times rapidly on `NEXT` or `BACK`
4. See flutter error

**Expected behavior**
No flutter error

**Comment by kengu** [comment]
@aagarwal1012 - I have a fix ready. As soon as #53 is accepted, I'll post the PR.

**Comment by aagarwal1012** [comment]
@kengu, I have merged your PR. Now you can post the PR corresponding to this issue.
