### ISSUE TITLE
Maintainer Required

### ISSUE THREAD

**Issue by aagarwal1012** [aagarwal1012/IntroViews-Flutter#66]
Due to multiple engagements and commitments, I am unable to devote time to solving issues and maintaining the package. Therefore, I strongly require someone who can spend his time to maintaining this repository.
Anyone interested can comment below and please start working on the current issues! In case of any difficultly, I am ready for a quick call to solve ambiguities.

**Comment by eyoeldefare** [comment]
Maybe you should ask https://github.com/matthew-carroll
What do you think?

**Comment by mzdm** [comment]
Hey, 👋 I would like to help to maintain this package. Firstly I would focus on fixing the issues and general code improvements (remove `new` keywords etc.) and finally do a migration to null safety. Then after getting familiar with the code I could work on some new features/improvements perhaps. 👍

**Comment by aagarwal1012** [comment]
@mzdm, thanks for your reply, I have sent you a `collaborator` invite, feel free to work on any issue.

**Comment by mzdm** [comment]
Thanks! I will get to them in a couple of days. A question: may I replace Travis with GitHub Actions (to run tests)? GitHub Actions are nowadays quite powerful and easier to maintain.

**Comment by aagarwal1012** [comment]
Sure @mzdm, replacing Travis with GitHub actions will definitely work. You can refer to https://github.com/aagarwal1012/Animated-Text-Kit/tree/master/.github/workflows for more info about it.
