### ISSUE TITLE
Page' is imported from both navigator and page

### ISSUE THREAD

**Issue by ggichure** [aagarwal1012/IntroViews-Flutter#69]
been getting this error
Compiler message:

> ../../../.pub-cache/hosted/pub.dartlang.org/intro_views_flutter-2.8.0/lib/intro_views_flutter.dart:241:11: Error: 'Page' is imported from both 'package:flutter/src/widgets/navigator.dart' and 'package:intro_views_flutter/UI/page.dart'.
>           Page(
>           ^^^^

**Comment by andymillernz** [comment]
Seems to be fixed in 2.8.1

You might need to force this in your pubspec.yaml file (`intro_views_flutter: ^2.8.1`) and run `flutter pub get`  again
