### ISSUE TITLE
On iOS small screens page overlaps bottom buttons

### ISSUE THREAD

**Issue by stefanop1** [aagarwal1012/IntroViews-Flutter#7]
- Device: [iPhone4S]
 - OS: [iOS9]
 - Version [2.0.1]

**Comment by aagarwal1012** [comment]
Could you please send a screenshot of the overlap. It would be helpful for me while resolving your problem.
😄

**Comment by aagarwal1012** [comment]
@taljacobson please have a look at this issue.

**Comment by stefanop1** [comment]
Il send you soon.
Thanks, Stefano

Il gio 28 giu 2018, 11:23 Ayush Agarwal <notifications@github.com> ha
scritto:

**Comment by stefanop1** [comment]
Here the screenshot.
The image size is the same of your example (256x256).
Thanks for your library, I'm new to flutter but need to make pratice as I
need for my next project.
Stefano

[image: IMG_0014.PNG]


Il giorno gio 28 giu 2018 alle ore 12:21 Stefano Pagliano <
spagliano@gmail.com> ha scritto:

**Comment by aagarwal1012** [comment]
Not getting the image 😞

**Comment by stefanop1** [comment]
Retry

[image: IMG_0014.png]


Il giorno gio 28 giu 2018 alle ore 19:54 Ayush Agarwal <
notifications@github.com> ha scritto:

**Comment by aagarwal1012** [comment]
I think this is problem of markdown, please send the image link.

**Comment by stefanop1** [comment]
My fault, using mail.
![img_0014](https://user-images.githubusercontent.com/8995697/42053085-e7e3b130-7b10-11e8-9970-3c4bc10d1501.png)

**Comment by aagarwal1012** [comment]
Issue Resolved. Thanks for the update. 👍
