### ISSUE TITLE
Enable body to take full height.

### ISSUE THREAD

**Issue by ChinHairSaintClair** [aagarwal1012/IntroViews-Flutter#81]
The problem I'm facing is when I provide a lengthy description or provide a more fleshed out body widget, the lack of space becomes an issue.

Ideally, I would like to adjust the ratio of the picture to body content, however,  another easier approach is to let the body take full height and managing the picture myself in the body section.

I have tried downloading the library myself and making the required changes to generate a module, however, I seem to keep running into build issues which seems to hint at outdated libraries or code in the project?

A possible simple update would be to alter the 'PageViewModel' to include a bool property that will enable a full-height body.
Then updating the '_buildPortraitPage' in the 'Page' model with a simple if wrapping the image item's 'Expanded' widget and using the 'PageViewModel's' new bool property as the evaluation in the if. The same can be used for the '__buildLandscapePage' method.
Unfortunately, I could not test this as not even run would work.

**Comment by mzdm** [comment]
This should be implemented in #91. It is not yet released on pub.dev so you can try it via:

```
  intro_views_flutter:
    git:
      url: git://github.com/aagarwal1012/IntroViews-Flutter.git
      ref: dev
```

which adds `pageBackground`. This way you can ignore body, title etc. and set your own order and proportions.

Please reopen if it is not what you wanted, thanks.
