### ISSUE TITLE
 No named parameter with the name 'resizeT oAvoidBottomPadding'.

### ISSUE THREAD

**Issue by wh120** [aagarwal1012/IntroViews-Flutter#82]
**Flutter version 2 with intro_views_flutter**
Hello 
After I update Flutter SDK to version 2  I get this error  in intro_views_flutter plugin
 Error: No named parameter with the name 'resizeToAvoidBottomPadding'.

**pubspec.yaml**
`intro_views_flutter: ^2.8.2`

**Console**

> C:\Users\wael1\AndroidStudioProjects\stem_cells>flutter build apk
> 
> Building without sound null safety
> For more information see https://dart.dev/null-safety/unsound-null-safety
> 
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/intro_views_flutter-2.8.2/lib/intro_views_flutter.dart:237:7: Error: No named parameter with the name 'resizeT
> oAvoidBottomPadding'.
>       resizeToAvoidBottomPadding: false,
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
>   const Scaffold({
>         ^^^^^^^^
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildRelease'.
> > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14m 9s
> Running Gradle task 'assembleRelease'...
> Running Gradle task 'assembleRelease'... Done                     851.7s
> Gradle task assembleRelease failed with exit code 1

**Comment by sherkot** [comment]
I have the same issue

**Comment by ir2pid** [comment]
any fix for this?

**Comment by timer-cp** [comment]
@sherkot @ir2pid , Hi, you can copy the plugin package from the cache of pub, then you can add it like a local dependence, also don't forget cancel resizeT oAvoidBottomPadding, I fixed this issure successfully.

**Comment by sherkot** [comment]
> @sherkot @ir2pid , Hi, you can copy the plugin package from the cache of pub, then you can add it like a local dependence, also don't forget cancel resizeT oAvoidBottomPadding, I fixed this issure successfully.

Hi @timer-cp, How to do these steps? Thank you for your help

**Comment by timer-cp** [comment]
@sherkot 
1. get plugin project from /fluttersdk/.pub-cache/hosted/pub.dartlang.org/intro_views_flutter-2.8.1, or clone from github 
2. remove the code : resizeToAvoidBottomPadding, and put the fixed plugin project in the plugins folder of the root project
3. dependence like this:
    intro_views_flutter:
    path: plugins/intro_views_flutter

**Comment by aagarwal1012** [comment]
#83 fixes this issue.

**Comment by aagarwal1012** [comment]
This issue should be fixed in `v2.9.0`.
